# Generated by Django 6.0.3 on 2026-03-18 03:54

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='package',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='package',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='package',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['status'], name='packages_pa_status_1e0453_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['receiver_city'], name='packages_pa_receive_b8e26e_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['tracking_number'], name='packages_pa_trackin_66fa4d_idx'),
        ),
    ]
