# Generated by Django 6.0.3 on 2026-04-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_package_height_alter_package_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='receiver_country',
            field=models.CharField(default='United Kingdom', max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='sender_country',
            field=models.CharField(default='United Kingdom', max_length=100),
        ),
    ]
