# Generated by Django 6.0.3 on 2026-04-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_standard', models.DecimalField(decimal_places=2, default=3.49, help_text='Standard delivery base price (2-3 days)', max_digits=6)),
                ('price_next_day', models.DecimalField(decimal_places=2, default=5.99, help_text='Next day delivery base price', max_digits=6)),
                ('price_same_day', models.DecimalField(decimal_places=2, default=12.99, help_text='Same day delivery base price', max_digits=6)),
                ('price_weight_1kg', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional cost for 0-1kg', max_digits=6)),
                ('price_weight_5kg', models.DecimalField(decimal_places=2, default=1.0, help_text='Additional cost for 1-5kg', max_digits=6)),
                ('price_weight_10kg', models.DecimalField(decimal_places=2, default=2.5, help_text='Additional cost for 5-10kg', max_digits=6)),
                ('price_weight_20kg', models.DecimalField(decimal_places=2, default=4.5, help_text='Additional cost for 10-20kg', max_digits=6)),
                ('price_weight_30kg', models.DecimalField(decimal_places=2, default=6.0, help_text='Additional cost for 20-30kg', max_digits=6)),
                ('price_weight_50kg', models.DecimalField(decimal_places=2, default=11.5, help_text='Additional cost for 30-50kg', max_digits=6)),
                ('price_insurance', models.DecimalField(decimal_places=2, default=2.99, help_text='Additional insurance', max_digits=6)),
                ('price_signature', models.DecimalField(decimal_places=2, default=1.5, help_text='Signature required', max_digits=6)),
                ('price_photo_proof', models.DecimalField(decimal_places=2, default=3.99, help_text='Photo proof of delivery', max_digits=6)),
                ('price_saturday', models.DecimalField(decimal_places=2, default=4.99, help_text='Saturday delivery', max_digits=6)),
                ('coverage_standard', models.DecimalField(decimal_places=2, default=50.0, help_text='Standard coverage amount (£)', max_digits=8)),
                ('coverage_next_day', models.DecimalField(decimal_places=2, default=100.0, help_text='Next day coverage amount (£)', max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
