# Generated by Django 6.0.3 on 2026-04-06 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_marker_opacity',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='Marker opacity (0.1 = faint, 1.0 = full brightness)', max_digits=2, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_marker_passed_color',
            field=models.CharField(default='#22c55e', help_text='Color for passed waypoint dots (hex, e.g. #22c55e = green)', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_marker_passed_size',
            field=models.PositiveIntegerField(default=6, help_text='Passed checkpoint dot size (3-15 pixels)', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_marker_truck_color',
            field=models.CharField(default='#dc2626', help_text='Truck marker background color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_marker_truck_size',
            field=models.PositiveIntegerField(default=60, help_text='Truck marker size (30-100 pixels)', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_marker_upcoming_color',
            field=models.CharField(default='#ef4444', help_text='Color for upcoming waypoint dots (hex, e.g. #ef4444 = red)', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_marker_waypoint_size',
            field=models.PositiveIntegerField(default=6, help_text='Waypoint dot size (3-15 pixels)', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_route_opacity',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='Route line opacity (0.1 = faint, 1.0 = full brightness)', max_digits=2, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_route_remaining_color',
            field=models.CharField(default='#ef4444', help_text='Color for remaining route line (hex, e.g. #ef4444 = red)', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_route_remaining_width',
            field=models.PositiveIntegerField(default=5, help_text='Width of remaining route line (1-20 pixels)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_route_traveled_color',
            field=models.CharField(default='#3b82f6', help_text='Color for traveled route line (hex, e.g. #3b82f6 = blue)', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_route_traveled_width',
            field=models.PositiveIntegerField(default=6, help_text='Width of traveled route line (1-20 pixels)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
