# Generated by Django 6.0.3 on 2026-03-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trackinghistory',
            index=models.Index(fields=['-timestamp'], name='tracking_tr_timesta_02f3c9_idx'),
        ),
    ]
