# Generated by Django 6.0.3 on 2026-04-06 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_add_country_fields'),
        ('tracking', '0002_trackinghistory_tracking_tr_timesta_02f3c9_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackinghistory',
            options={'ordering': ['-timestamp', '-id'], 'verbose_name_plural': 'Tracking histories'},
        ),
        migrations.CreateModel(
            name='RouteWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(help_text='City/location name shown on map', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in the route (0 = first stop)')),
                ('is_passed', models.BooleanField(default=False, help_text='Has the truck passed this waypoint?')),
                ('notes', models.CharField(blank=True, help_text='Optional notes for this stop', max_length=200)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_waypoints', to='packages.package')),
            ],
            options={
                'verbose_name': 'Route Waypoint',
                'verbose_name_plural': 'Route Waypoints',
                'ordering': ['package', 'order'],
                'unique_together': {('package', 'order')},
            },
        ),
    ]
